### ISSUE TITLE
DOS Protocol scheme

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-repository-service-schemas#49] opened 2018-02-26 23:15 UTC
* Should we suggest a usage like `s3://` for `dos://`? 
* What parts should be in the URL? 
* Can you set the API version? Is the point to obscure the API path (`ga4gh/dos/v1`)?
* How do you set the object version? 
* Does it assume the port DOS runs on? 80/443?
* Data Bundles and Data Objects are addressed differently in the API, how does a client know when its an Object or Bundle being requested? Check both?

```
dos://host/UUID?version=abc
# or do you need the type?
dos://host/dataobjects/UUID?version=abc
# What if its running at a different port?
dos://host:8080/dataobjects/UUID?version=abc
```

**Comment by dvoet** [comment] 2018-02-27 14:38
The initial use case for a dos scheme is storage. Systems need to store references to objects in dos systems. These references need to be resolvable at some unknown future time so need to be resilient to api versions and url structure changes. To this end a dos URI should contain only the minimum information necessary to identify an object. This should be location (i.e. server:port), UUID and version:
`dos://<server>:<port>/<uuid>?version=<version>`

Changes in api version or structure should be handled by any service responsible for interpreting a dos URI.

RE dataobject vs. databundles - I don't understand why the dos api makes a distinction at the request level. The response specifies if a thing is a bundle or an object. Given a UUID why should a client know a priori if it is a bundle or not?

**Comment by dvoet** [comment] 2018-02-27 14:41
the reason we need that at all instead of just storing an entire http url is that systems also need to recognize that these are dos objects and not just some other random url

**Comment by geoffjentry** [comment] 2018-02-27 15:59
👍 to both things @dvoet said. 

In particular, the URI should definitely use something like `dos://` as otherwise it'll be impossible to work out in an automatic fashion if one is looking at a DOS URI or something else.

**Comment by david4096** [comment] 2018-03-01 19:24
Thanks @geoffjentry and @dvoet! I write a quick notebook in hopes of pushing this conversation forward here, where I simply replace `https` with `dos` for our current URLs: https://gist.github.com/david4096/db6fe055eeac9554f5f0407364375d0c

I would like to separate out the issues of gathering UUIDs from the basepath of the service (#51) and the `dos://` protocol scheme, which should be understood as stating "use a DOS/http client for messages returned from this service". 

This would mean that a dos:// address made following the URL scheme in the notebook would work today, and if we pushed forward with the schema change, would also support simpler paths in the future. 

Please let me know your thoughts!

**Comment by david4096** [comment] 2018-04-13 23:09
For reference https://github.com/broadinstitute/martha

**Comment by dvoet** [comment] 2018-04-15 06:32
The problem is that these URIs will be in countless database records and
spreadsheets scattered across the planet. They must work now and 5 years
from now and beyond. So, having the api version in the URI is detrimental -
what happens to all the database records out there when we rev the api?
Having the rest of the boiler plate is just a waste of space as it provides
no information. And do we really want to be stuck with it for eternity?

What is the benefit of just swapping the scheme? Is it just that it is
easy? I don’t think transforming what we currently have for dos URIs is
much harder.

**Comment by david4096** [comment] 2018-05-03 17:10
During the face to face we discussed using the DOS protocol scheme for representing GUIDs. The indexd service allows prefix lookup. A simpler scheme would include the protocol and the GUID.

**Comment by david4096** [comment] 2018-05-31 01:08
By using a combination of prefix services and identifier resolvers we expect the dos url scheme to look something like `dos://MY-PREFIX/MY-ID?version=MY-VERSION`. This should allow items to be resolved uniquely to a prefix namespace.

**Comment by tetron** [comment] 2018-05-31 18:13
The linked data perspective is to use DNS as the prefix or namespace (otherwise you need another bespoke resolver service).  So MY-PREFIX should be the hostname of the DOS service.

We should register any URL schemes with the IANA:

https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

Fortunately "dos" isn't claimed yet.  On the other hand, I don't know if IANA has a policy about adding new schemes for http based protocols.  There are other ways to determine if a given http endpoint is actually a DOS service, such as custom headers, or content negotiation.

**Comment by dvoet** [comment] 2018-05-31 18:30
I don't really care about the format of the identifier as I am just going to pass it on to a resolution service to interpret. But I do need to determine from the identifier alone that it is a DOS identifier. That precludes any kind of header or content negotiation approaches.

We have also agreed that we will have another resolver service so MY-PREFIX will not be a DNS hostname.

**Comment by tetron** [comment] 2018-05-31 18:45
I think using dos:// url scheme is fine, but we should make an effort to register it.

What's the reasoning for having another resolver service for the prefix?  Do you have a link to the discussion?  (I don't see anything about it on this ticket).

**Comment by dvoet** [comment] 2018-05-31 18:48
The decision was made during a project face to face meeting. To me the clincher is that it give the resolving service the freedom to direct to a local version of the data.

**Comment by tetron** [comment] 2018-05-31 18:51
That seems like a separate issue.  By analogy with DNS, a site can run a local DOS service to which it sends its request, which could be resolved either to a locally cached copy, or contact the authoritative source.

**Comment by tetron** [comment] 2018-05-31 19:13
From the Toronto F2F Data Access meeting: consensus that the prefix should be a hostname.

**Closed** 2019-02-25 21:04 UTC
Labels: Project: DRS, Status: Help Wanted, Type: Documentation, Type: Question, to-be-deleted-on-2019-02-22

**Comment by dvoet** [comment] 2019-02-25 21:54
Why was this closed? Is there a resolution?
