### ISSUE TITLE
Intermittent test failure in test.test_server.TestServer

### ISSUE THREAD

**Issue by natanlao** [ga4gh/data-repository-service-schemas#169] opened 2018-09-11 23:00 UTC
It looks like #166 introduced a test that fails only sometimes. I've observed this behavior on Travis and on both Python 2.7 and 3.6. [Example traceback here.](https://travis-ci.org/ga4gh/data-object-service-schemas/jobs/427437884#L646)

I'm particularly interested in refactoring `setUpClass` for that test suite anyway to not use Popen (over some built-in testing facility that may or may not exist in bravado). This might be a good excuse to do it.

**Comment by cricketsloan** [comment] 2018-11-14 18:49
➤ Natan Lao commented:

I cannot reproduce this error. The work that I anticipate would be required to close this ticket were I able to reproduce it is specified in \#189. As such, I am rejecting this ticket

**Closed by cricketsloan** 2018-11-14 18:49 UTC
